config/routes.rb
Rails.application.routes.draw do
  root to: "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, length: { minimum: 3, maximum: 20 }
  validates :age, numericality: { only_integer: true, greater_than_or_equal_to: 0 } 
  validates :cuteness, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
  validates :softness, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  def edit
    
  end

  def update
    if @kitten.update(kitten_params)
      flash[:success] = "Sucessfully edited this kitten!"
      redirect_to @kitten
    else
      flash.now[:danger] = "Can't update this kitten. There are errors in your form."
      render "edit"
    end
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Successfully created a kitten!"
      redirect_to @kitten
    else 
      flash.now[:danger] = "Can't create this kitten. There are some errors in your form."
      render "new"
    end
  end

  def destroy
    flash[:info] = "#{@kitten.name} has been deleted."
    @kitten.destroy
    redirect_to root_path
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<% if @kitten.errors.any? %>
  <div id="error-msg">
    <ul id="error-list">
      <% @kitten.errors.full_messages.each do |msg| %>
        <li class="msg"><span><%= msg %></span></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @kitten do |form| %>

  <div id="form-container" class="form-divs">

    <div class="form-divs">
      <%= form.label :name, class: "label" %><br>
      <%= form.text_field :name, class: "input" %>
    </div>

    <div class="form-divs">
      <%= form.label :age, class: "label" %><br>
      <%= form.number_field :age, class: "input" %>
    </div>

    <div class="form-divs">
      <%= form.label :cuteness, "Cuteness (Out of 10)", class: "label" %><br>
      <%= form.number_field :cuteness, class: "input" %>
    </div>

    <div class="form-divs">
      <%= form.label :softness, "Softness (Out of 10)", class: "label" %><br>
      <%= form.number_field :softness, class: "input" %>
    </div>

  </div>

  <div id="btn-container" class="form-divs">
    <%= form.submit "Submit", id: "new-btn" %>
  </div>

<% end %>

app/views/kittens/edit.html.erb
<%= render "shared/flash" %>
<h1 id="edit-title">Edit Kitten</h1>
<%= render "form" %>

<%= link_to @kitten, id: "cancel-edit" do  %>
  <div id="cancel-div">Cancel</div>
<% end %>

app/views/kittens/index.html.erb
<%= render "shared/flash" %>

<h1 id="title-kitten-index">Kittens</h1>

<a href="<%= "#{kittens_url}.json" %>" target="_blank" id="title-kitten-index" style="display: block; font-size: 20px; margin-bottom: 30px;">JSON API Output</a>

<div id="container">

  <a id="new-link" href=<%= new_kitten_path %>>
    <div id="green">
      <div id="add-container">

          <div></div>

          <img id="plus" src="images/add.png" height="42", width="42">

          <p id="new-kitten-btn">New Kitten</p>

          <div></div>

      </div>
    </div>
  </a>

  <div id="table-container">
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Age</th>
          <th>Cuteness</th>
          <th>Softness</th>
        </tr>
      </thead>

      <tbody>
        <% @kittens.each do |kitten| %>
          <tr>
            <td><%= kitten.name %></td>
            <td><%= kitten.age %></td>
            <td><%= kitten.cuteness %></td>
            <td><%= kitten.softness %></td>

            <td><%= link_to kitten do %>
              <img src="/images/view.png" class="options" height="40" width="40">
            <% end %></td>

            <td><%= link_to edit_kitten_path(kitten) do %>
              <img src="/images/edit.png" class="options" height="40" width="40">
            <% end %></td>
            <td><%= link_to kitten, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <img src="/images/delete.png" class="options" height="40" width="40">
            <% end %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/kittens/new.html.erb
<%= render "shared/flash" %>
<h1 id="new-title">New Kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<%= render "shared/flash" %>

<a href="<%= "#{kitten_url}.json" %>" target="_blank" id="title-kitten-index" style="display: block; font-size: 20px; margin: 30px 0 30px 0;">JSON API Output</a>

<div id="detail-container">
  <h1 id="kitten-name">Kitten: <%= @kitten.name %></h1>
  <p class="detail">
    <strong>Name:</strong> <%= @kitten.name %>
  </p>

  <p class="detail">
    <strong>Age:</strong> <%= @kitten.age %>
  </p>

  <p class="detail">
    <strong>Cuteness:</strong> <%= @kitten.cuteness %>
  </p>

  <p class="detail">
    <strong>Softness:</strong> <%= @kitten.softness %>
  </p>

  <div id="links">
  
    <a id="back-link" href=<%= root_path %>>
      <img class="show-btn" src="/images/back.png" height="40" width="40"></a>
    </a>

    <a id="edit-show" href=<%= edit_kitten_path %>><img class="show-btn" src="/images/edit-white.png" height="40" width="40"></a>

    <%= link_to @kitten, method: :delete, data: { confirm: 'Are you sure?' }, id: "delete-show" do %>
      <img class="show-btn" src="/images/delete-white.png" class="options" height="40" width="40">
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div id="navbar">
  <a id="home" href=<%= root_path %>>
    <img id="cat-logo" src="/images/logo.png" alt="cat logo" height="90" width="90">
  </a>

  <a id="kittens-nav" href=<%= root_path %>>
    <h1 id="k-title">Kittens</h1>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Red+Hat+Display:ital,wght@1,500&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="bg">
      <%= render 'layouts/navbar' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <% flash.each do |status, msg| %>
    <div class="notification"><%= msg %></div>
  <% end %>
<% end %>